### PR TITLE
Allow particular logging messages to be ignored.

### PR DESCRIPTION
**Pull request by AaronC81**
Adds #57.

(There is also a minor bug fix in here relating to Commander, where running without Bundler would cause an uninitialized constant error.)

### CODE REVIEW

**Comment by AaronC81** [comment]
@connorshea - if you could please give this a quick look over before I merge it, that'd be fab! Hesitant to push it straight into master as it's difficult to test.

**Comment by AaronC81** [comment]
Good shout - done!

**Comment by connorshea** [comment]
It seems to work as far as I can tell. I do kind of wonder whether 'done' messages should be included by default, even if the user doesn't explicitly include them with `--include-messages` (`--exclude-messages=done` should work regardless).

**Comment by AaronC81** [comment]
That's a neat idea, I'll add that now.

**Comment by connorshea** [comment]
But yeah, other than that it seems to work 👍

**Pull request merged**
