### PR TITLE
Ability to exclude untyped methods

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by AaronC81** [comment]
This is a great change to have, thank you! 

I think it would be good to also have a test for this. You can add this if you like, but I'm also happy to add a test if you don't get a chance - just let me know :)

**Comment by wagenet** [comment]
I'll try to see if I can add one tomorrow.

**Comment by wagenet** [comment]
@AaronC81 obviously I didn't get to adding one yet! I can probably do it next week if you don't get to it sooner.

**Comment by AaronC81** [comment]
No worries @wagenet! I've added a test, and also fixed an issue I found while adding it.

In Parlour, comments need to be associated with a "typed object" (e.g. method, class, etc), but here we're explicitly _not_ generating a method if it's untyped. So the "excluding untyped" log message would never be added as a comment like other log messages are, unless some other typed method definition followed.

I've added a wonky workaround by generating these particular comments themselves as typed objects. Seems to work alright!

Feel free to leave any comments about the code I've added, otherwise I'll merge it in a few days :)

**Review by wagenet — COMMENTED** [review]
This seems good to me. Hacks are never my favorite (and I'm sure they're not yours), but I don't have any better suggestions here!

**Comment by AaronC81** [comment]
Indeed - never a fan of a hack, but I think fixing this in a "proper" way would need some rather complex additions to Parlour. I doubt comments not associated with a typed object are a particularly common use-case anyway. 

I'll get this merged then - cheers for taking a look :)

**Pull request merged**
