### PR TITLE
Update sorbet/rbi/gems with 'srb rbi gems'.

### PR DESCRIPTION
**Pull request by connorshea**
I was trying out the sorbet VS Code extension and it was complaining about Colorizer's string methods not existing, so I updated the sorbet gem definitions.

### CODE REVIEW

**Comment by AaronC81** [comment]
Great!

"Fun" story which is semi-related: I wrote an RBI for Colorize on a fork of sorbet-typed, but when I try to PR it, GitHub 500 errors...

image

**Comment by connorshea** [comment]
...huh, that's bizarre

**Comment by connorshea** [comment]
You might want to report that to GitHub support, I get the same thing when trying to open a PR of your branch :D

**Comment by AaronC81** [comment]
I already have done, and they're apparently looking into it!

**Pull request merged**
